import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join, resolve } from 'path';

import { createConsoleLogger } from '../../log/console.js';
import { fileURLToPath } from '../../url/index.js';
import { isGenerateTestDataEnabled } from '../test_data.js';

/** Writes the contents specified to the target file if test data generation is enabled. */
export function writeTestData(targetFileFromRepoRoot: string, contents: string | Buffer, raw: boolean = false) {
  if (!isGenerateTestDataEnabled()) {
    return;
  }
  const targetFile = getPathToFile(targetFileFromRepoRoot);
  const toWrite = raw ? contents : typeof contents === 'string' ? contents : contents.toString('hex');
  writeFileSync(targetFile, toWrite);
  const logger = createConsoleLogger('aztec:testing:test_data');
  logger(`Wrote test data to ${targetFile}`);
}

export function readTestData(repoPath: string): Buffer {
  const targetFile = getPathToFile(repoPath);
  return readFileSync(targetFile);
}

/**
 * Looks for a variable assignment in the target file and updates the value, only if test data generation is enabled.
 * Note that a magic inline comment would be a cleaner approach, like `/* TEST-DATA-START *\/` and `/* TEST-DATA-END *\/`,
 * but running nargo fmt on it panics since the comment would be erased, so we roll with this for now.
 * @remarks Requires AZTEC_GENERATE_TEST_DATA=1 to be set
 */
export function updateInlineTestData(targetFileFromRepoRoot: string, itemName: string, value: string) {
  if (!isGenerateTestDataEnabled()) {
    return;
  }
  updateInlineTestDataAt(getPathToFile(targetFileFromRepoRoot), itemName, value);
}

/**
 * Same as {@link updateInlineTestData}, for a target that lives in the foundation repository this one is a submodule
 * of rather than in this one. The path is relative to the foundation repository root.
 * @remarks Requires AZTEC_GENERATE_TEST_DATA=1 to be set
 */
export function updateInlineFndTestData(targetFileFromFndRoot: string, itemName: string, value: string) {
  if (!isGenerateTestDataEnabled()) {
    return;
  }
  updateInlineTestDataAt(getPathToFndFile(targetFileFromFndRoot), itemName, value);
}

function updateInlineTestDataAt(targetFile: string, itemName: string, value: string) {
  const logger = createConsoleLogger('aztec:testing:test_data');
  const contents = readFileSync(targetFile, 'utf8').toString();
  const regex = new RegExp(`(let|pub\\s+global)\\s+${itemName}(\\s*:\\s*[^=]+)?\\s*=\\s*([\\s\\S]*?);`, 'g');
  if (!regex.exec(contents)) {
    throw new Error(`Test data marker for ${itemName} not found in ${targetFile}`);
  }

  const updatedContents = contents.replace(
    regex,
    (_, declareKeyword, typeAnnotation) =>
      `${declareKeyword} ${itemName}${(typeAnnotation || '').trimEnd()} = ${value};`,
  );
  writeFileSync(targetFile, updatedContents);
  logger(`Updated test data in ${targetFile} for ${itemName} to ${value}`);
}

/**
 * Updates the sample Prover.toml files in the foundation repository's noir-projects/fnd/noir-protocol-circuits/crates/.
 * @remarks Requires AZTEC_GENERATE_TEST_DATA=1 to be set. The block-root, block-merge, checkpoint,
 * tx-merge, and root rollup samples are regenerated by the prover-client
 * `regenerate_rollup_sample_inputs.test.ts` suite; the private-kernel and transaction-base rollup
 * samples by the e2e 'AZTEC_GENERATE_TEST_DATA=1 FAKE_PROOFS=1 yarn test:e2e single-node/prover/server/full.test' dump.
 */
export function updateProtocolCircuitSampleInputs(circuitName: string, value: string) {
  const logger = createConsoleLogger('aztec:testing:test_data');
  const targetFileFromFndRoot = `noir-projects/fnd/noir-protocol-circuits/crates/${circuitName}/Prover.toml`;
  const targetFile = getPathToFndFile(targetFileFromFndRoot);
  writeFileSync(targetFile, value);
  logger(`Updated test data in ${targetFile} for ${circuitName}`);
}

/**
 * Resolves the output path for an l1-contracts test fixture. The `l1-contracts` project lives in the foundation
 * repository, which is not an ancestor of this checkout, so regenerating fixtures from here requires pointing
 * `AZTEC_L1_FIXTURES_DIR` at `l1-contracts/test/fixtures` in the foundation tree. The fallback is the historical path
 * relative to the running package's working directory.
 */
export function getL1FixturePath(fileName: string) {
  return join(process.env.AZTEC_L1_FIXTURES_DIR ?? '../../l1-contracts/test/fixtures', fileName);
}

export function getPathToFile(targetFileFromRepoRoot: string) {
  const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../../');
  if (!existsSync(join(repoRoot, 'CODEOWNERS'))) {
    throw new Error(`Path to repo root is incorrect (got ${repoRoot})`);
  }

  return join(repoRoot, targetFileFromRepoRoot);
}

/**
 * Resolves a path relative to the root of the foundation repository (aztec-packages), which checks this repository out
 * as its `labs` submodule. Test data that lives in the protocol circuits is only committed there, so regenerating it
 * means writing one directory above this repository's root.
 */
export function getPathToFndFile(targetFileFromFndRoot: string) {
  const fndRoot = resolve(dirname(fileURLToPath(import.meta.url)), '../../../../../../');
  if (!existsSync(join(fndRoot, 'CODEOWNERS')) || !existsSync(join(fndRoot, 'labs-patches'))) {
    throw new Error(
      `Cannot resolve ${targetFileFromFndRoot}: ${fndRoot} is not an aztec-packages checkout. ` +
        `This fixture is committed in aztec-packages, not in this repository, so it can only be regenerated from an ` +
        `aztec-packages checkout with this repository checked out as its labs submodule.`,
    );
  }

  return join(fndRoot, targetFileFromFndRoot);
}
