#!/usr/bin/env bash
source $(git rev-parse --show-toplevel)/ci3/source_bootstrap

# Used for build.
function hash {
  # Nothing under noir-projects/fnd is an input: everything it produces reaches us as a pinned
  # package, hashed via yarn.lock (covered by the yarn-project patterns).
  hash_str \
    $(../labs-aztec-toolchain/bootstrap.sh hash) \
    $(../noir-projects/labs/noir-contracts/bootstrap.sh hash) \
    $(cache_content_hash ../yarn-project/.rebuild_patterns)
}

# Base folded into every dependency hash: everything an entry can depend on that the
# dependency closures (scripts/dep-closures.mjs) don't cover — yarn.lock, .swcrc, jest
# configs, scripts, fixtures — plus the toolchain hash. Unlike the build hash, noir-contracts
# is NOT folded in: the generated contract TS and artifact JSONs are closure members and are
# content-hashed per entry (see compute_package_dep_hashes), so a contract change only
# invalidates the tests whose closures reach it. Everything under yarn-project is in by
# default so new fixture types can't silently fall outside the base; the exclusions are
# .ts (covered by the closures — .tsx/.mts/.cts stay in, excluding them isn't worth it and
# including them only over-invalidates), files that can't affect test behavior (docs,
# terraform, images), and per-package package.json manifests, which dep-closures.mjs adds
# to each closure that spans the package — so a manifest change only moves the keys of
# entries that reach it. The root yarn-project/package.json (workspaces, resolutions) and
# any deeper fixture package.json stay in the base.
function hash_deps_base {
  hash_str \
    $(../labs-aztec-toolchain/bootstrap.sh hash) \
    $(cache_content_hash '^yarn-project/' \
        '!^yarn-project/.*\.(ts|md|tf|svg|png)$' \
        '!^yarn-project/[^/]+/package\.json$')
}

# Prints a test's cache key from the map produced by compute_dep_hashes. The keys only
# matter to CI's redis test cache, so outside CI this always prints disabled-cache (the token
# both cache layers treat as "never cache") — local runs never read the map, so a stale local
# map can't poison anything. A missing map or entry likewise disables caching for that test
# rather than risking a stale hit.
function dep_hash {
  local h=
  if [ "$CI" -eq 1 ]; then
    h=$(awk -v t="$1" '$1 == t { print $2; exit }' .dep-hashes 2>/dev/null || true)
  fi
  echo "${h:-disabled-cache}"
}

# Dumps the whole per-test cache-key map ("<test> <hash>" per line) so other bootstraps
# (end-to-end) can load it into memory once instead of invoking dep_hash per test.
function dep_hashes {
  cat .dep-hashes 2>/dev/null || true
}

# Prints the cache key of a non-test entry point registered in compute_dep_hashes
# (e.g. txe/src/bin/index.ts), for other bootstraps to compose their test hashes from.
# Outside CI prints disabled-cache like dep_hash. In CI a missing map or entry is a hard
# error: it means the entry point was never registered, and degrading silently would leave
# the caller's tests keyed on nothing.
function require_dep_hash {
  if [ "$CI" -ne 1 ]; then
    echo disabled-cache
    return
  fi
  local h
  h=$(awk -v t="$1" '$1 == t { print $2; exit }' .dep-hashes 2>/dev/null || true)
  if [ -z "$h" ]; then
    echo_stderr "ERROR: no dependency hash for '$1' in yarn-project/.dep-hashes." \
      "Register it in compute_dep_hashes and rebuild."
    exit 1
  fi
  echo "$h"
}

# One parallel unit of compute_dep_hashes: computes the closures of one package's tests
# (batched into a single ts.Program by dep-closures.mjs) and prints one "<test> <hash>" line per
# test, paths relative to yarn-project to match test_cmds. The hash is the final cache key:
# hash_deps_base (passed as $base, hashed once per compute rather than once per test_cmds
# line) plus the git blob hashes of the closure members in closure order (the closure is
# path-sorted, so this is deterministic). Blobs come from $lstree, a single ls-tree dump shared
# by all workers — memoized by the caller so the same file is never ls-tree'd once per test.
# Closure members absent from the dump (untracked generated sources, dest/*.d.ts leaves)
# contribute nothing and are covered by the other hash_deps_base components, matching
# cache_content_hash's tracked-files-only behavior.
function compute_package_dep_hashes {
  set -euo pipefail
  local pkg=$1 entries_file=$2 lstree=$3 base=$4
  local out=$(dirname "$lstree")/$pkg
  node scripts/dep-closures.mjs $(grep "^$pkg/" "$entries_file") > "$out.closures"

  # Closure members absent from the ls-tree dump are untracked build outputs (generated
  # contract TS, artifact JSONs, generated data files): hash their working-tree content. This
  # runs right after the build (re)generated them, and the map ships in the same artifact, so
  # the hashes always describe the generated bytes they travel with — and a contract change
  # only moves the keys of tests whose closures reach its generated files. Paths stay
  # repo-relative: git hash-object --stdin-paths resolves them from the repo root, not cwd.
  awk 'NR == FNR { blob[$4] = 1; next } /^[^#]/ && NF && !($0 in blob)' "$lstree" "$out.closures" \
    | sort -u | while read -r f; do [ -f "../$f" ] && echo "$f" || true; done > "$out.untracked"
  git hash-object --stdin-paths < "$out.untracked" > "$out.wthashes"
  paste -d' ' "$out.untracked" "$out.wthashes" > "$out.wtmap"

  # awk writes each test's key preimage ("<base> <hashes...>", the exact bytes hash_str would
  # hash) to its own file and prints the test name; one git hash-object --stdin-paths call
  # then hashes all of them, instead of one hash_str subprocess per test.
  awk -v base="$base" -v out="$out" '
      function flush() { if (t) { f = out "." n++; print line > f; close(f); print t } }
      FILENAME == ARGV[1] { blob[$4] = $3; next }
      FILENAME == ARGV[2] { blob[$1] = $2; next }
      /^# / { flush(); t = substr($0, 3); line = base; next }
      NF && ($0 in blob) { line = line " " blob[$0] }
      END { flush() }
    ' "$lstree" "$out.wtmap" "$out.closures" > "$out.tests"
  paste -d' ' <(sed 's|^yarn-project/||' "$out.tests") \
    <(seq 0 $(($(wc -l < "$out.tests") - 1)) | sed "s|^|$out.|" | git hash-object --stdin-paths | cut -c1-16)
}

# Computes the per-test dependency-hash map (gitignored .dep-hashes) consumed by
# dep_hash. Runs at the end of compile_all: since the map is gitignored it ships inside the
# yarn-project build artifact (cache_upload sweeps all ignored files), keyed by the full
# content hash — so a downloaded or freshly built tree always carries a map that is current
# for its content, with no separate staleness tracking. Dirty-tree handling is delegated to
# cache_content_hash: uncommitted changes disable caching (and error in CI).
function compute_dep_hashes {
  echo_header "yarn-project compute dependency hashes"

  # The map was called .test-dep-hashes until 2026-08-20; a stale copy left by an older
  # build is no longer gitignored and would dirty the tree. Remove this line once
  # lingering checkouts have had time to churn (a few months).
  rm -f .test-dep-hashes

  # Refuse to build a map from dishonest closures: every detectable dynamic-load site
  # (workers, non-literal imports, forks) must carry a // @dependency annotation. The check
  # is fast and runs everywhere; the map generation below is CI-only — local runs never read
  # the map (dep_hash prints disabled-cache outside CI), so computing it is wasted minutes.
  local start=$SECONDS
  node scripts/dep-closures.mjs --check
  echo "Dependency check took $((SECONDS - start))s."
  if [ "${CI:-0}" -ne 1 ]; then
    return
  fi
  start=$SECONDS

  local commit=${AZTEC_CACHE_COMMIT:-HEAD}
  local tmp=$(mktemp -d)

  {
    find . -name '*.test.ts' -not -path '*node_modules*' -not -path '*/dest/*' | sed 's|^\./||'
    # Non-test entry points other bootstraps key their test caches on via require_dep_hash:
    # the TXE server and oracle test resolver that noir-contracts/aztec-nr nargo tests run against.
    echo txe/src/bin/index.ts
    echo txe/src/bin/oracle_test_server.ts
  } | sort > $tmp/entries

  # Closures are computed from the working tree but keys are hashed from $commit's blobs, so
  # tree and commit must agree. cache_content_hash implements the canonical contract (dirty →
  # disabled-cache, dirty in CI → error, explicit AZTEC_CACHE_COMMIT → check skipped): probe
  # .ts dirt with it directly; hash_deps_base's own cache_content_hash covers everything
  # else. Either disabled means every key is disabled — write the map directly and skip the
  # closure computation.
  local ts_hash base
  ts_hash=$(cache_content_hash '^yarn-project/.*\.ts$')
  base=$(hash_deps_base)
  if [[ "$ts_hash" == "disabled-cache" || "$base" == "disabled-cache" ]]; then
    sed 's/$/ disabled-cache/' $tmp/entries > .dep-hashes
    rm -rf $tmp
    return
  fi

  # All closure members live under yarn-project/; one dump serves every worker.
  git -C .. ls-tree -r "$commit" -- yarn-project > $tmp/lstree
  cut -d/ -f1 $tmp/entries | sort -u \
    | parallel --memsuspend 16G "compute_package_dep_hashes {} $tmp/entries $tmp/lstree $base > $tmp/hashes-{}"
  sort $tmp/hashes-* > $tmp/out && mv $tmp/out .dep-hashes
  rm -rf $tmp
  echo "Dependency hash generation took $((SECONDS - start))s."
}

function compile_project {
  # TODO: 16 jobs is magic. Was seeing weird errors otherwise.
  parallel -j16 --line-buffered --tag 'cd {} && ../node_modules/.bin/swc src -d dest --config-file=../.swcrc --strip-leading-paths' "$@"
}

# Returns a list of project paths to compile/lint/publish.
# Ensure exclusions are matching in both cases.
function get_projects {
  if [ "${1:-}" == 'topological' ]; then
    yarn workspaces foreach --topological-dev -A \
      --exclude @aztec/aztec3-packages \
      --exclude @aztec/scripts \
      exec 'echo $(pwd)' | cat | grep -v "Done"
  else
    dirname */src | xargs realpath
  fi
}

function format {
  local arg="-w"
  local packages=()

  # Parse all arguments
  while [ $# -gt 0 ]; do
    case "$1" in
      --check)
        arg="--check"
        ;;
      -w|--write)
        arg="-w"
        ;;
      -*)
        echo "Unknown flag: $1" >&2
        return 1
        ;;
      *)
        packages+=("$1")
        ;;
    esac
    shift
  done

  # Build the paths array to search
  local paths=()
  if [ ${#packages[@]} -eq 0 ]; then
    paths=(./*/src)
  else
    for pkg in "${packages[@]}"; do
      if [ ! -d "./$pkg/src" ]; then
        echo "Error: Package '$pkg' not found or has no src directory" >&2
        return 1
      fi
      paths+=("./$pkg/src")
    done
  fi

  find "${paths[@]}" -type f -regex '.*\.\(json\|js\|mjs\|cjs\|ts\)$' | \
    parallel -N30 ./node_modules/.bin/prettier --log-level warn "$arg"
}

function lint {
  local arg="--fix"
  local packages=()

  # Parse all arguments
  while [ $# -gt 0 ]; do
    case "$1" in
      --check)
        arg=""
        ;;
      --fix)
        arg="--fix"
        ;;
      -*)
        echo "Unknown flag: $1" >&2
        return 1
        ;;
      *)
        packages+=("$1")
        ;;
    esac
    shift
  done

  if [ ${#packages[@]} -gt 0 ]; then
    # Validate packages exist
    for pkg in "${packages[@]}"; do
      if [ ! -d "./$pkg/src" ]; then
        echo "Error: Package '$pkg' not found or has no src directory" >&2
        return 1
      fi
    done
    # Lint specified packages in parallel (use at most half of CPU cores)
    printf '%s\n' "${packages[@]}" | parallel -j 50% "cd {} && ../node_modules/.bin/eslint --cache $arg ./src"
  else
    # Lint all packages in parallel (use at most half of CPU cores)
    get_projects | parallel -j 50% "cd {} && ../node_modules/.bin/eslint --cache $arg ./src"
  fi
}

function compile_all_projects {
  get_projects | compile_project
}

function compile_all {
  set -euo pipefail
  local hash=$(hash)
  if cache_download yarn-project-$hash.tar.gz; then
    return
  fi

  # Ensure the pinned version sqlite3mc-wasm upstream artifacts are present before any package builds.
  ./sqlite3mc-wasm/scripts/vendor.sh ensure

  # produce constants.gen.ts before compiling the constants package.
  constants/scripts/remake-constants.sh

  compile_project ::: constants foundation stdlib blob-lib builder ethereum

  # Call all projects that have a generation stage.
  parallel --joblog joblog.txt --line-buffered --tag 'cd {} && yarn generate' ::: \
    accounts \
    aztec.js \
    cli \
    slasher \
    stdlib \
    ivc-integration \
    noir-contracts.js \
    noir-test-contracts.js \
    noir-protocol-circuits-types \
    protocol-contracts \
    pxe \
    standard-contracts
  cat joblog.txt

  get_projects | compile_project

  cd txe && yarn build
  cd ..

  # Run oracle version checks after compilation
  cd pxe && yarn check_oracle_version
  cd ..
  cd txe && yarn check_txe_oracle_version
  cd ..

  cmds=('format --check' 'yarn tsgo -b --emitDeclarationOnly')
  if [ "${CI:-0}" -eq 1 ]; then
    cmds+=('lint --check')
  fi
  parallel --joblog joblog.txt --tag denoise ::: "${cmds[@]}"
  cat joblog.txt

  # Runs after the block above: closure resolution walks the dest/*.d.ts that tsgo emits.
  # The map is gitignored, so the upload below carries it inside the build artifact.
  compute_dep_hashes

  if [ "$CI" -eq 1 ]; then
    cache_upload "yarn-project-$hash.tar.gz" $(git ls-files --others --ignored --exclude-standard | grep -v '^node_modules/')
  fi
}

# The @aztec/l1-artifacts foundry bundle references solc by version (a portable npm
# package cannot ship a platform binary), so the runtime forge deploy resolves it through
# ~/.svm. The e2e containers run without network and inherit ~/.svm from the host's home
# mount, so warm it at build time. The version is read from the installed bundle, so it
# cannot drift from what the deploy will request.
function warm_solc_cache {
  local foundry_toml=node_modules/@aztec/l1-artifacts/l1-contracts/foundry.toml
  [ -f "$foundry_toml" ] || return 0
  local solc_version=$(sed -n 's/^solc_version = "\(.*\)"$/\1/p' "$foundry_toml")
  # A bundle that ships its own solc binary (solc = "./solc-x.y.z") needs no warming.
  [ -n "$solc_version" ] || return 0
  [ -f "$HOME/.svm/$solc_version/solc-$solc_version" ] && return 0
  echo_stderr "Warming solc $solc_version into ~/.svm for the offline forge deploy path..."
  # svm-rs only uses ~/.svm if it exists (falling back to XDG dirs otherwise), so make sure
  # it does: the deploy path inside the containers must find the binary at this exact path.
  mkdir -p "$HOME/.svm"
  local tmp=$(mktemp -d)
  mkdir -p "$tmp/src"
  printf '[profile.default]\nsolc_version = "%s"\n' "$solc_version" > "$tmp/foundry.toml"
  printf '// SPDX-License-Identifier: MIT\npragma solidity ^0.8.0;\ncontract Warm {}\n' > "$tmp/src/Warm.sol"
  # svm fetches from binaries.soliditylang.org, which intermittently fails to resolve under
  # heavy parallel CI load; retry only on connection/DNS failures so real errors fail fast.
  RETRY_ATTEMPTS=30 RETRY_SLEEP=10 retry -p 'dns error|Temporary failure in name resolution|error sending request|failed to lookup address|Connection refused|connection reset' \
    "cd $tmp && forge build"
  rm -rf "$tmp"
  if [ ! -f "$HOME/.svm/$solc_version/solc-$solc_version" ]; then
    echo_stderr "ERROR: forge/svm did not install solc $solc_version into ~/.svm."
    exit 1
  fi
}

export -f compile_project format lint get_projects compile_all hash warm_solc_cache \
  compute_package_dep_hashes compute_dep_hashes hash_deps_base

function build {
  echo_header "yarn-project build"
  denoise "./bootstrap.sh clean-lite"
  npm_install_deps
  denoise "warm_solc_cache"
  denoise "compile_all"
}

function test_cmds {
  # Exclusions:
  # end-to-end: e2e tests handled separately with end-to-end/bootstrap.sh.
  # kv-store: per-file fan-out handled by kv-store/bootstrap.sh test_cmds.
  for test in !(end-to-end|kv-store|aztec)/src/**/*.test.ts; do
    # Skip benchmarks here.
    [[ "$test" =~ \.bench\.test\.ts$ ]] && continue

    local prefix=$(dep_hash "$test")
    local cmd_env=""

    # These need isolation due to network stack usage (p2p, anvil, etc).
    if [[ "$test" =~ ^(prover-node|p2p|ethereum|aztec|prover-client/src/test|stdlib/src/l1-contracts|ivc-integration/src/chonk_browser|blob-client/src/server) ]]; then
      prefix+=":ISOLATE=1:NAME=$test"
    fi

    if [[ "$test" =~ ^ivc-integration/src/chonk_browser ]]; then
      prefix+=":NET=1"
    fi

    # Boost some tests resources.
    if [[ "$test" =~ testbench ]]; then
      prefix+=":CPUS=10:MEM=16g"
    elif [[ "$test" =~ avm_proving_tests || "$test" =~ rollup_ivc_integration || "$test" =~ avm_integration ]]; then
      prefix+=":CPUS=16:MEM=16g"
    elif [[ "$test" =~ ^ivc-integration/ ]]; then
      prefix+=":CPUS=8"
    fi

    # Add debug logging for tests that require a bit more info
    if [[ "$test" == p2p/src/client/p2p_client.test.ts || "$test" == p2p/src/services/discv5/discv5_service.test.ts || "$test" == p2p/src/client/p2p_client.integration.test.ts ]]; then
      cmd_env+=" LOG_LEVEL=\"debug; info: json-rpc, simulator\""
    elif [[ "$test" =~ rollup_ivc_integration || "$test" =~ avm_integration ]]; then
      cmd_env+=" LOG_LEVEL=\"debug; info: json-rpc, simulator\" BB_VERBOSE=1 "
    elif [[ "$test" =~ e2e_p2p ]]; then
      cmd_env+=" LOG_LEVEL='verbose; debug:p2p'"
    fi

    # Enable real proofs in prover-client integration tests only on CI full.
    if [[ "$test" =~ ^prover-client/src/test/ ]]; then
      if [ "$CI_FULL" -eq 1 ]; then
        prefix+=":CPUS=16:MEM=96g"
        cmd_env+=" LOG_LEVEL=verbose HARDWARE_CONCURRENCY=16"
      else
        cmd_env+=" FAKE_PROOFS=1"
      fi
    fi

    echo "${prefix}${cmd_env} yarn-project/scripts/run_test.sh $test"
  done

  # kv-store: per-file fan-out (mocha for node tests, vitest for browser tests).
  kv-store/bootstrap.sh test_cmds

  # Aztec CLI tests
  aztec/bootstrap.sh test_cmds

  if [[ "${TARGET_BRANCH:-}" =~ ^(v[0-9]+(-next)?|backport-to-v[0-9]+-(staging|next))$ ]]; then
    for test in aztec/src/testnet_compatibility.test.ts aztec/src/mainnet_compatibility.test.ts; do
      echo "$(dep_hash "$test") yarn-project/scripts/run_test.sh $test"
    done
  fi
}

function test {
  echo_header "yarn-project test"
  test_cmds | filter_test_cmds | parallelize
}

function bench_cmds {
  local hash=$(hash)
  echo "$hash BENCH_OUTPUT=bench-out/sim.bench.json yarn-project/scripts/run_test.sh simulator/src/public/public_tx_simulator/apps_tests/bench.test.ts"
  echo "$hash BENCH_OUTPUT=bench-out/native_world_state.bench.json yarn-project/scripts/run_test.sh world-state/src/native/native_bench.test.ts"
  echo "$hash BENCH_OUTPUT=bench-out/kv_store.bench.json yarn-project/scripts/run_test.sh kv-store/src/bench/map_bench.test.ts"
  echo "$hash BENCH_OUTPUT=bench-out/tx_pool_v2.bench.json yarn-project/scripts/run_test.sh p2p/src/mem_pools/tx_pool_v2/tx_pool_v2_bench.test.ts"
  echo "$hash BENCH_OUTPUT=bench-out/tx_validator.bench.json yarn-project/scripts/run_test.sh p2p/src/msg_validators/tx_validator/tx_validator_bench.test.ts"
  echo "$hash:ISOLATE=1:CPUS=16:MEM=32g:TIMEOUT=1800 BENCH_OUTPUT=bench-out/p2p_client_batch_tx_requester.bench.json yarn-project/scripts/run_test.sh p2p/src/client/test/p2p_client.batch_tx_requester.bench.test.ts"
  echo "$hash BENCH_OUTPUT=bench-out/tx.bench.json yarn-project/scripts/run_test.sh stdlib/src/tx/tx_bench.test.ts"
  echo "$hash:ISOLATE=1:CPUS=10:MEM=16g:LOG_LEVEL=silent BENCH_OUTPUT=bench-out/proving_broker.bench.json yarn-project/scripts/run_test.sh prover-client/src/test/proving_broker_testbench.test.ts"
  echo "$hash:ISOLATE=1:CPUS=16:MEM=16g BENCH_OUTPUT=bench-out/avm_bulk_test.bench.json yarn-project/scripts/run_test.sh bb-prover/src/avm_proving_tests/avm_bulk.test.ts"
  echo "$hash BENCH_OUTPUT=bench-out/lightweight_checkpoint_builder.bench.json yarn-project/scripts/run_test.sh prover-client/src/light/lightweight_checkpoint_builder.bench.test.ts"
  echo "$hash:ISOLATE=1:CPUS=8:MEM=32g:TIMEOUT=1200 BENCH_OUTPUT=bench-out/batch_verifier.bench.json yarn-project/scripts/run_test.sh ivc-integration/src/batch_verifier.bench.test.ts"
}

function release_packages {
  echo "Computing packages to publish..."
  local packages=$(get_projects topological)

  # Scoped release (see ci3/release_prep_package_json): only the @aztec deps local to this
  # workspace are co-published at $1; foundation deps keep the version the root resolutions
  # field pins them to.
  local resolutions
  resolutions="$(jq -c '.resolutions // {}' package.json)"
  export NPM_RELEASE_RESOLUTIONS="$resolutions"

  # Validate every manifest before anything is published: deploy_npm applies the same
  # scoped-release rules per package inside the loop below, where a failure would abort
  # the release with earlier packages already live on npm.
  echo "Validating package manifests..."
  for package in $packages; do
    (cd $package && release_prep_package_json --check "$1")
  done

  local package_list=()
  for package in $packages; do
    (cd $package && retry "deploy_npm $1")
    local package_name=$(jq -r .name "$package/package.json")
    package_list+=("$package_name@$1")
  done
  # Smoke test the deployed packages.
  local dir=$(mktemp -d)
  cd "$dir"
  do_or_dryrun npm init -y
  # NOTE: originally this was on one line, but sometimes snagged downloading end-to-end (most recently published package).
  # --no-audit --no-fund: npm's implicit audit re-scans the whole cumulative tree on every install, dominating
  # release time. Dependency vulnerabilities are covered by the weekly socket-fix workflow instead.
  # npm publish is eventually consistent: a just-published version can take a few minutes to
  # become installable, so give each install a ~5 minute window instead of the default ~10s.
  for package in "${package_list[@]}"; do
    RETRY_ATTEMPTS=10 RETRY_SLEEP=30 retry "do_or_dryrun npm install --no-audit --no-fund $package"
  done
  rm -rf "$dir"
}

function release {
  echo_header "yarn-project release"
  release_packages "${REF_NAME#v}"
}

case "$cmd" in
  "clean")
    [ -n "${1:-}" ] && cd $1
    git clean -fdx
    ;;
  "clean-lite")
    # Preserve gitignored fixture dirs that are populated by sibling builds and
    # consumed concurrently by parallel test commands. Wiping them mid-test
    # yanks files out from under readers (e.g. the pinned Chonk inputs download).
    files=$(git ls-files --ignored --others --exclude-standard | grep -vE '(node_modules/|^\.yarn/|^tmp/|^end-to-end/example-app-ivc-inputs-out/|^end-to-end/ultrahonk-bench-inputs/|^end-to-end/dumped-avm-circuit-inputs/)' || true)
    if [ -n "$files" ]; then
      echo "$files" | xargs rm -rf
    fi
    ;;
  "")
    build
    ;;
  "compile")
    if [ -n "${1:-}" ]; then
      compile_project ::: "$@"
    else
      get_projects | compile_project
    fi
    ;;
  instrumented_profile)
    # Automatically hooks sites with benchmarking instrumentation.
    if [ "$#" -gt 1 ]; then
      echo "Usage: ./bootstrap.sh profile <command>"
      exit 1
    fi
    cmd=$1
    # Refuse to continue if there are uncommitted changes to tracked files.
    if [ -n "$(git status --porcelain | grep -v '^??')" ]; then
      echo "Please commit or stash your changes before running this command."
      exit 1
    fi
    rm -f profile-*.json
    echo "NOTE: If you interrupt this you may have a dirty git state or build state. Otherwise it will clean up."
    ( cd ./scripts/instrumenting-profiler && npm install )
    ./scripts/instrumenting-profiler/instrument.sh
    denoise "./bootstrap.sh compile"
    pwd=$(pwd)
    cleanup_instrumentation() {
      # we may have changed paths
      git checkout "$pwd"
      denoise "cd '$pwd' && ./bootstrap.sh compile"
      for f in profile-*.json; do
        echo "To print: ./scripts/instrumenting-profiler/print.mjs $(pwd)/$f"
      done
    }
    trap cleanup_instrumentation EXIT
    eval "$cmd"
    ;;
  *)
    default_cmd_handler "$@"
    ;;
esac
